name: Secrets and Environments

on:
  workflow_dispatch:

env:
  RELEASE_VERSION: v1.0

jobs:
  staging-environment:
    runs-on: ubuntu-24.04
    environment: staging
    env:
      # Inject Repository-Level Secret & Variable into the shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}

      # Inject Environment-Level Secret & Variable into the shell
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
    steps:
      - name: Inspect values inside the Job (Staging)
        run: |
          echo "Repo Secret (masked)        : $EXAMPLE_REPOSITORY_SECRET"
          echo "Repo Variable               : $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Environment Secret (masked) : $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Environment Variable        : $EXAMPLE_ENVIRONMENT_VARIABLE"

  production-environment:
    runs-on: ubuntu-24.04
    environment: production
    env:
      # Inject Repository-Level Secret & Variable into the shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}

      # Inject Environment-Level Secret & Variable into the shell
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
    steps:
      - name: Inspect values inside the Job (Production)
        run: |
          echo "Repo Secret (masked)        : $EXAMPLE_REPOSITORY_SECRET"
          echo "Repo Variable               : $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Environment Secret (masked) : $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Environment Variable        : $EXAMPLE_ENVIRONMENT_VARIABLE"